// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tmvsygnspbyqwejglwnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRtdnN5Z25zcGJ5cXdlamdsd25iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI0NzE2MDQsImV4cCI6MjA3ODA0NzYwNH0.0XMlHsmrg6suZfn50mvDapS19ljDVmB4QrUVjK9Mad4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});